/**
 * Generates supabase/seed.sql from the typed seed data in this directory.
 * Run with `npx tsx supabase/seed-data/generate.ts` (or `npm run seed:gen`)
 * whenever the menu/ingredients/customer list changes — the output file is
 * checked in and consumed by `supabase db reset`, not generated at reset
 * time, so there's no live DB dependency to regenerate it.
 *
 * IDs are assigned here (not left to gen_random_uuid() defaults) so
 * recipe_items / order_items can reference menu_items / ingredients by a
 * value this script controls, in a single static SQL file.
 */

import { randomUUID } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { SEED_INGREDIENTS } from "./ingredients";
import { SEED_MENU } from "./menu";
import { SEED_CUSTOMER_NAMES } from "./customers";
import { generateOrderHistory } from "../../lib/domain/seed-generation";

// Fixed seed so the generated file is reproducible between runs — easier to
// review a diff when re-running doesn't reshuffle everything. The runtime
// reset action (app/admin/admincontrols) seeds generateOrderHistory differently, on
// purpose — see lib/domain/seed-generation.ts.
const GENERATOR_SEED = 20260828;

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlTimestamp(date: Date): string {
  return `'${date.toISOString()}'`;
}

// ---------------------------------------------------------------------
// ingredients

const ingredientIds = new Map<string, string>();
const ingredientRows: string[] = [];

for (const ing of SEED_INGREDIENTS) {
  const id = randomUUID();
  ingredientIds.set(ing.name, id);
  const containerSize = ing.containerSize ?? null;
  ingredientRows.push(
    `  (${sqlString(id)}, ${sqlString(ing.name)}, ${sqlString(ing.unit)}, ${ing.stockQuantity}, ${ing.lowStockThreshold}, ${containerSize})`,
  );
}

// ---------------------------------------------------------------------
// menu_items + recipe_items

const menuItemIds = new Map<string, string>();
const menuItemRows: string[] = [];
const recipeItemRows: string[] = [];

SEED_MENU.forEach((item, index) => {
  const id = randomUUID();
  menuItemIds.set(item.name, id);
  menuItemRows.push(
    `  (${sqlString(id)}, ${sqlString(item.name)}, ${sqlString(item.description)}, ${sqlString(item.moodTag)}, ${item.priceCents}, false, null, ${index})`,
  );

  for (const ingredient of item.recipe) {
    const ingredientId = ingredientIds.get(ingredient.ingredientName);
    if (!ingredientId) {
      throw new Error(
        `Recipe for "${item.name}" references unknown ingredient "${ingredient.ingredientName}" — add it to seed-data/ingredients.ts`,
      );
    }
    recipeItemRows.push(
      `  (${sqlString(id)}, ${sqlString(ingredientId)}, ${ingredient.quantityRequired})`,
    );
  }
});

// ---------------------------------------------------------------------
// orders + order_items
//
// Generated by the shared algorithm in lib/domain/seed-generation.ts (also
// used by the runtime admin reset action) — see that file for the
// weekday/weekend curve, busy-day roll, and cafe-hours timestamp logic.

const menuEntries = SEED_MENU.map((item) => ({
  id: menuItemIds.get(item.name)!,
  priceCents: item.priceCents,
}));

const generatedOrders = generateOrderHistory({
  seed: GENERATOR_SEED,
  menu: menuEntries,
  customerNames: SEED_CUSTOMER_NAMES,
});

const orderRows: string[] = [];
const orderItemRows: string[] = [];

for (const order of generatedOrders) {
  const orderId = randomUUID();
  orderRows.push(
    `  (${sqlString(orderId)}, ${sqlString(order.customerName)}, ${sqlString(order.status)}, ${order.totalCents}, ${sqlTimestamp(order.createdAt)})`,
  );
  for (const line of order.lines) {
    orderItemRows.push(
      `  (${sqlString(randomUUID())}, ${sqlString(orderId)}, ${sqlString(line.menuItemId)}, ${line.quantity}, ${line.unitPriceCents})`,
    );
  }
}

// ---------------------------------------------------------------------
// assemble

const sql = `-- Generated by supabase/seed-data/generate.ts — do not hand-edit.
-- Regenerate with: npx tsx supabase/seed-data/generate.ts
--
-- Restored automatically by \`supabase db reset\`. ${SEED_INGREDIENTS.length} ingredients,
-- ${SEED_MENU.length} menu items, ${orderRows.length} orders spanning the last
-- 90 days, generated ${new Date().toISOString()}.

begin;

insert into ingredients (id, name, unit, stock_quantity, low_stock_threshold, container_size)
values
${ingredientRows.join(",\n")};

insert into menu_items (id, name, description, mood_tag, price_cents, is_sold_out, sold_out_reason, display_order)
values
${menuItemRows.join(",\n")};

insert into recipe_items (menu_item_id, ingredient_id, quantity_required)
values
${recipeItemRows.join(",\n")};

insert into orders (id, customer_name, status, total_cents, created_at)
values
${orderRows.join(",\n")};

insert into order_items (id, order_id, menu_item_id, quantity, unit_price_cents)
values
${orderItemRows.join(",\n")};

commit;
`;

const outPath = fileURLToPath(new URL("../seed.sql", import.meta.url));
writeFileSync(outPath, sql, "utf-8");

console.log(`Wrote ${outPath}`);
console.log(
  `${SEED_INGREDIENTS.length} ingredients, ${SEED_MENU.length} menu items, ${recipeItemRows.length} recipe rows, ${orderRows.length} orders, ${orderItemRows.length} order items`,
);
